instaclone/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

instaclone/instaclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^.', include('users.urls', namespace='users')),
    url(r'^', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaclone/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^upload_photo/$', views.upload_photo, name='upload_photo'),
    url(r'^update_profile', views.update_profile, name='update_profile'),
    url(r'^search', views.search, name='search'),
    url(r'^(?P<username>[\w\d]+)/$', views.profile, name='profile'),
]

instaclone/core/models.py
from django.db import models

# Create your models here.

instaclone/users/models.py
import os
import hashlib
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import transaction
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User


def get_upload_path_profile(instance, filename):
    ext = os.path.splitext(filename)
    profile_photos_path = 'ugc\\profile_photos\\{}\\profile_photo{}'.format(instance.user.id, ext[1])
    return profile_photos_path


def get_upload_path_other(instance, filename):
    ext = os.path.splitext(filename)[-1]
    new_name = hashlib.md5(os.path.splitext(filename)[0].encode('utf-8')).hexdigest()
    new_name += ext
    other_photos_path = 'ugc\\other_photos\\{}\\{}\\{}'.format(new_name[:2], new_name[2:4], new_name)
    return other_photos_path


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.CharField(max_length=300, blank=True, null=True)
    photo = models.ImageField(upload_to=get_upload_path_profile, blank=True, null=True,
                              default=settings.DEFAULT_AVATAR)

    def __str__(self):
        return str(self.user)


class Photo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=get_upload_path_other)
    tags = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField()

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        self.created = timezone.now()
        return super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
@transaction.atomic
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

instaclone/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile, Photo



class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ('about', 'photo')


class PhotoForm(ModelForm):

    class Meta:
        model = Photo
        fields = ['photo', 'tags']

instaclone/core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {'user': request.user}
    return render(request, 'core/index.html', context=context)

instaclone/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .models import Profile, Photo
from .forms import UserForm, ProfileForm, PhotoForm


@login_required
def profile(request, username):
    editable = False
    user_info = Profile.objects.get(user__username=username)
    if request.user == user_info.user:
        editable = True
    try:
        user_photos = Photo.objects.filter(user=user_info.user)
    except Photo.DoesNotExist:
        user_photos = None

    context = {'user_info': user_info, 'user_photos': user_photos, 'editable': editable}
    return render(request, 'users/profile.html', context=context)


@login_required
def upload_photo(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form_object = form.save(commit=False)
            form_object.user = request.user
            form.save()
            return redirect('users:profile', request.user.username)
    form = PhotoForm()
    context = {'form': form}
    return render(request, 'users/upload_photo.html', context=context)


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
            return redirect('users:profile', username= request.user.username)
        else:
            messages.error(request, 'Please correct the error below')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'users/update_profile.html', context=context)


@login_required
def search(request):
    if request.method == 'GET':
        query = request.GET.get('query', None)
        if query is not None:
            query = query.strip().lower()
            query_user = get_object_or_404(User, username=query)
            return redirect('users:profile', username=query_user.username)
        else:
            return redirect('users:profile', username=request.user.username)

instaclone/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | instaClone</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <style>
        body{
            font-family : Roboto, Verdana, Geneva, Arial, Helvetica, sans-serif;
        }
        {% block style %} {% endblock %}
    </style>
</head>
<body>
    {% include 'includes/header.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

instaclone/templates/core/index.html
{% extends 'base.html' %}
{% block title %} Start Sharing {% endblock %}
{% block content%}
    <h1> You have seen it before </h1>
{% endblock %}

instaclone/templates/includes/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'core:index' %}">Instaclone</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% if user.is_authenticated %}
                <form class="navbar-form navbar-left" action="{% url 'users:search' %}" method="get">
                    <div class="form-group">
                        <input type="text" name="query" placeholder="Find a friend" required="True">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{user.username}} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'users:profile' user.username %}"> Profile </a></li>
                            <li><a href="{% url 'users:update_profile' %}">Update profile</a></li>
                            <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'account_login' %}">Login</a></li>
                    <li><a href="{% url 'account_signup' %}">Register</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

instaclone/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{user_info.user.username}} {% endblock %}
{% block style %}
    .user-info{
        margin-left: 40%;
        padding-bottom: 50px;
    }
    .profile-picture{
        border-radius: 10px;
        border: solid 3px #b30000;
    }
    #upload-photo{
        padding-top: 10px;
    }
    #upload-photo a{
        padding: 7px;
        border-radius: 10px;
        background-color: #b30000;
        text-decoration: none;
        color: white;
    }
{% endblock %}
{% block content %}
    <div class="user-info">
        <img class="profile-picture" src="{{user_info.photo.url}}" height="200" width="200">
        <h3>{{user_info.user.username}}</h3>
        {% if user_info.about %}
            <h5>{{ user_info.about }}</h5>
        {% endif %}
        {% if editable %}
            <div id="upload-photo"><a href="{% url 'users:upload_photo' %}"> Upload photo </a></div>
        {% endif %}
    </div>

    <div class=" jumbotron container user-content">
        {% if user_photos is not None %}
            {% for photo in user_photos %}
                {% if forloop.first %}
                    <div class="row">{% endif %}
                        <div class="col-xs-3">
                            <a class="thumbnail" href="{{photo.photo.url}}"><img  src={{photo.photo.url}}></a>
                        </div>
                        {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
                {% if forloop.last%}</div>{% endif %}
            {% endfor %}
        {% else %}
            <h3> Still haven't uploaded pictures</h3>
        {% endif %}
    </div>
{% endblock %}

instaclone/templates/users/update_profile.html
{% extends 'base.html' %}
{% block title %} Update profile {% endblock %}
{% block content %}
    <div class="update-profile-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <button type="submit">Update</button>
        </form>

    </div>
{% endblock %}

instaclone/templates/users/upload_photo.html
{% extends 'base.html' %}
{% block title %} Upload Photo {% endblock%}
{% block content %}
    <h3>Upload a new photo </h3>
    <div class="photo_form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Upload </button>
        </form>
    </div>

{% endblock %}